// apps/portfolio-react-mf/src/App.tsx
import { useMemo, useState, useEffect } from 'react'
import './App.css'
import {
  getMicrofrontendBus,
  getMicrofrontendTabId,
  getMicrofrontendChannel,
  validateTabMessage,
  validateMultiTabMessage,
  sanitizeDisplayString,
  MF_CONFIG,
  type TabMessage,
  type MultiTabMessage,
} from '@mf/shared'

type Message = {
  id: number
  from: string
  scope: 'tab' | 'multi-tab'
  count: number
  timestamp: string
}

function getInstanceId(container?: HTMLElement): string {
  if (!container) return crypto.randomUUID()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const instances = (window as any).__MF_INSTANCES__
  return instances?.get(container) || crypto.randomUUID()
}

function App({ container }: { container?: HTMLElement }) {
  const [clicks, setClicks] = useState(0)
  const [externalClicks, setExternalClicks] = useState(0)
  const [messages, setMessages] = useState<Message[]>([])

  const instanceId = useMemo(() => getInstanceId(container), [container])

  const level = useMemo(() => {
    if (clicks >= 8) return 'alto'
    if (clicks >= 4) return 'medio'
    return 'inicial'
  }, [clicks])

  const levelClass = useMemo(() => `level-${level}`, [level])

  useEffect(() => {
    try {
      const bus = getMicrofrontendBus()
      const channel = getMicrofrontendChannel()
      const tabId = getMicrofrontendTabId()
      
      const tabHandler = (payload: TabMessage) => {
        try {
          validateTabMessage(payload)
          // Filtrar mensajes de esta misma instancia
          if (payload.instanceId !== instanceId) {
            // Solo actualizar externalClicks si viene del mismo framework pero diferente instancia
            if (payload.source === 'react') {
              setExternalClicks(payload.count)
            }
            setMessages(prev => [...prev, {
              id: Date.now(),
              from: sanitizeDisplayString(payload.source),
              scope: 'tab',
              count: payload.count,
              timestamp: new Date().toLocaleTimeString()
            }])
          }
        } catch (error) {
          if (import.meta.env.DEV) {
            console.warn('[React] Invalid tab message:', error)
          }
        }
      }

      // Escuchar multi-tab DIRECTAMENTE del BroadcastChannel 
      const multiTabHandler = (event: MessageEvent) => {
        try {
          const payload = event.data
          validateMultiTabMessage(payload)
          if (payload.tabId !== tabId) {
            setMessages(prev => [...prev, {
              id: Date.now() + 1,
              from: sanitizeDisplayString(payload.source),
              scope: 'multi-tab',
              count: payload.count,
              timestamp: new Date().toLocaleTimeString()
            }])
          }
        } catch (error) {
          if (import.meta.env.DEV) {
            console.warn('[React] Invalid multi-tab message:', error)
          }
        }
      }

      bus.on('click-count', tabHandler)
      
      if (channel) {
        channel.addEventListener('message', multiTabHandler)
      }
      
      return () => {
        try {
          bus.off('click-count', tabHandler)
          if (channel) {
            channel.removeEventListener('message', multiTabHandler)
          }
        } catch (err) {
          console.error('Error limpiando listeners:', err)
        }
      }
    } catch (err) {
      console.error('Error configurando event bus:', err)
    }
  }, [instanceId])

  const handleClick = () => {
    try {
      const bus = getMicrofrontendBus()
      const newCount = clicks + 1
      setClicks(newCount)
      const payload: TabMessage = { source: 'react', count: newCount, instanceId }
      validateTabMessage(payload)
      bus.emit('click-count', payload)
    } catch (err) {
      console.error('[React] Failed to handle click:', err)
    }
  }

  const sendToTab = () => {
    try {
      const bus = getMicrofrontendBus()
      const payload: TabMessage = { source: 'react', count: clicks, instanceId }
      validateTabMessage(payload)
      bus.emit('click-count', payload)
    } catch (err) {
      console.error('[React] Failed to send tab message:', err)
    }
  }

  const sendToMultiTab = () => {
    try {
      const channel = getMicrofrontendChannel()
      if (!channel) {
        if (import.meta.env.DEV) {
          console.warn('[React] BroadcastChannel not available')
        }
        return
      }
      const tabId = getMicrofrontendTabId()
      const payload: MultiTabMessage = { source: 'react', count: clicks, tabId, instanceId }
      validateMultiTabMessage(payload)
      channel.postMessage(payload)
    } catch (err) {
      console.error('[React] Failed to send multi-tab message:', err)
    }
  }

  return (
    <section className="react-card">
      <h3>React Micro-Frontend</h3>
      <p>Renderizado dentro del shell Astro con hooks.</p>
      <div className="react-stats">
        <span>Clicks: {clicks}</span>
        <span className={`level-pill ${levelClass}`}>Nivel: {level}</span>
        {externalClicks > 0 && (
          <span className="external-clicks">Desde otros: {externalClicks}</span>
        )}
      </div>
      <button className="react-btn" type="button" onClick={handleClick}>
        Probar hook useState
      </button>

      <div className="event-controls">
        <button className="react-btn-secondary" type="button" onClick={sendToTab}>
          📤 Enviar a Tab (EventBus)
        </button>
        <button className="react-btn-secondary" type="button" onClick={sendToMultiTab}>
          🌐 Multi-tab (BroadcastChannel)
        </button>
      </div>

      {messages.length > 0 && (
        <div className="messages-log">
          <h4>Mensajes recibidos:</h4>
          <ul>
            {messages.slice(-MF_CONFIG.MAX_MESSAGES_IN_LOG).reverse().map(msg => (
              <li key={msg.id}>
                <strong>{msg.scope}</strong> de <em>{msg.from}</em>: count={msg.count} ({msg.timestamp})
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  )
}

export default App

// apps/portfolio-angular-mf/src/presentation/app/app.ts
import { Component, computed, signal, OnInit, OnDestroy, ElementRef, inject } from '@angular/core';
import {
  getMicrofrontendBus,
  getMicrofrontendTabId,
  getMicrofrontendChannel,
  validateTabMessage,
  validateMultiTabMessage,
  sanitizeDisplayString,
  MF_CONFIG,
  EventBus,
  type TabMessage,
  type MultiTabMessage,
  type MicroFrontendEvents,
} from '@mf/shared';
import { environment } from '../../environments/environment';

interface Message {
  id: number;
  from: string;
  scope: 'tab' | 'multi-tab';
  count: number;
  timestamp: string;
}

@Component({
  selector: 'portfolio-angular-mf',
  template: `
    <section class="angular-card">
      <div class="mfe-header">
        <h3>Angular Micro-Frontend</h3>
        <div class="mfe-badges">
          <span class="mfe-badge angular">Angular 21</span>
          <span
            class="mfe-badge"
            [class.env-dev]="!envProduction()"
            [class.env-prod]="envProduction()"
          >
            {{ envName() }}
          </span>
        </div>
      </div>
      <p>Renderizado dentro del shell Astro con signals.</p>
      <div class="angular-stats">
        <span>Clicks: {{ clicks() }}</span>
        <span
          class="level-pill"
          [class.level-inicial]="level() === 'inicial'"
          [class.level-medio]="level() === 'medio'"
          [class.level-alto]="level() === 'alto'"
        >
          Nivel: {{ level() }}
        </span>
        @if (externalClicks() > 0) {
          <span class="external-clicks">Desde otros: {{ externalClicks() }}</span>
        }
      </div>
      <button class="angular-btn" type="button" (click)="increment()">Probar signal()</button>

      <div class="event-controls">
        <button class="angular-btn-secondary" type="button" (click)="sendToTab()">
          📤 Enviar a Tab (EventBus)
        </button>
        <button class="angular-btn-secondary" type="button" (click)="sendToMultiTab()">
          🌐 Multi-tab (BroadcastChannel)
        </button>
      </div>

      @if (messages().length > 0) {
        <div class="messages-log">
          <h4>Mensajes recibidos:</h4>
          <ul>
            @for (msg of messages().slice(-MF_CONFIG.MAX_MESSAGES_IN_LOG).reverse(); track msg.id) {
              <li>
                <strong>{{ msg.scope }}</strong> de <em>{{ msg.from }}</em>: count={{ msg.count }} ({{ msg.timestamp }})
              </li>
            }
          </ul>
        </div>
      }
    </section>
  `,
  styleUrl: './app.css'
})
export class App implements OnInit, OnDestroy {
  private elementRef = inject(ElementRef);
  private instanceId: string = '';

  clicks = signal(0);
  externalClicks = signal(0);
  messages = signal<Message[]>([]);

  // Environment signals (detecta dev vs prod)
  readonly envProduction = signal(environment.production);
  readonly envName = computed(() =>
    this.envProduction() ? '🔴 PROD' : '🟢 DEV'
  );

  private bus!: EventBus<MicroFrontendEvents>;

  // Expose MF_CONFIG to template
  readonly MF_CONFIG = MF_CONFIG;

  level = computed(() => {
    const value = this.clicks();
    if (value >= 8) return 'alto';
    if (value >= 4) return 'medio';
    return 'inicial';
  });

  private tabHandler = (payload: TabMessage) => {
    try {
      validateTabMessage(payload);
      // Filtrar mensajes de esta misma instancia
      if (payload.instanceId !== this.instanceId) {
        // Solo actualizar externalClicks si viene del mismo framework pero diferente instancia
        if (payload.source === 'angular') {
          this.externalClicks.set(payload.count);
        }
        this.messages.update(prev => [...prev, {
          id: Date.now(),
          from: sanitizeDisplayString(payload.source),
          scope: 'tab',
          count: payload.count,
          timestamp: new Date().toLocaleTimeString()
        }]);
      }
    } catch (error) {
      console.warn('[Angular] Invalid tab message:', error);
    }
  };

  private multiTabHandler = (event: MessageEvent) => {
    try {
      const payload = event.data;
      validateMultiTabMessage(payload);
      // Filtrar mensajes de la misma tab (solo mostrar los de otras tabs)
      const tabId = getMicrofrontendTabId();
      if (payload.tabId !== tabId) {
        this.messages.update(prev => [...prev, {
          id: Date.now() + 1,
          from: sanitizeDisplayString(payload.source),
          scope: 'multi-tab',
          count: payload.count,
          timestamp: new Date().toLocaleTimeString()
        }]);
      }
    } catch (error) {
      console.warn('[Angular] Invalid multi-tab message:', error);
    }
  };

  private channel: BroadcastChannel | null = null;

  ngOnInit() {
    try {
      // Obtener instanceId del elemento host
      const hostElement = this.elementRef.nativeElement as HTMLElement;
      this.instanceId = hostElement.getAttribute('data-instance-id') || crypto.randomUUID();

      this.bus = getMicrofrontendBus<MicroFrontendEvents>();
      this.channel = getMicrofrontendChannel();

      this.bus.on('click-count', this.tabHandler);

      if (this.channel) {
        this.channel.addEventListener('message', this.multiTabHandler);
      }
    } catch (error) {
      console.error('[Angular] Error in ngOnInit:', error);
    }
  }

  ngOnDestroy() {
    if (this.bus) {
      this.bus.off('click-count', this.tabHandler);
    }
    if (this.channel) {
      this.channel.removeEventListener('message', this.multiTabHandler);
    }
  }

  increment() {
    try {
      const newCount = this.clicks() + 1;
      this.clicks.update((value) => value + 1);
      const payload: TabMessage = { source: 'angular', count: newCount, instanceId: this.instanceId };
      validateTabMessage(payload);
      this.bus.emit('click-count', payload);
    } catch (error) {
      console.error('[Angular] Failed to increment:', error);
    }
  }

  sendToTab() {
    try {
      const payload: TabMessage = { source: 'angular', count: this.clicks(), instanceId: this.instanceId };
      validateTabMessage(payload);
      this.bus.emit('click-count', payload);
    } catch (error) {
      console.error('[Angular] Failed to send tab message:', error);
    }
  }

  sendToMultiTab() {
    try {
      const channel = getMicrofrontendChannel();
      if (!channel) {
        console.warn('[Angular] BroadcastChannel not available');
        return;
      }
      const tabId = getMicrofrontendTabId();
      const payload: MultiTabMessage = { source: 'angular', count: this.clicks(), tabId, instanceId: this.instanceId };
      validateMultiTabMessage(payload);
      channel.postMessage(payload);
    } catch (error) {
      console.error('[Angular] Failed to send multi-tab message:', error);
    }
  }
}
